import type { Metadata } from "next";

import "./globals.css";

import {Header} from "./componentes/header";
import {Footer} from "./componentes/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`antialiased`}>
          <Header/>
            <main>{children}</main>
          <Footer/>
      </body>
    </html>
  );
}
